FROM python:3.10

COPY requirements.txt .

# RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet') ; nltk.download('stopwords')"

RUN python -c "import nltk; nltk.download('omw-1.4');"

COPY . .

EXPOSE 5000

